_wandb:
    value:
        cli_version: 0.24.2
        e:
            s07fdgbwns03dzusbamap4ybv49qqjpx:
                codePath: c:\Users\ADMIN\Documents\projects\team\Dlthon_01_Motocycle_Night_Ride\jong-ha\resnet50_baseline_aug.ipynb
                codePathLocal: resnet50_baseline_aug.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1023177388032"
                        used: "989166669824"
                email: kimjongha611@gmail.com
                executable: c:\Users\ADMIN\Documents\projects\team\Dlthon_01_Motocycle_Night_Ride\.venv\Scripts\python.exe
                git:
                    commit: e9ba2b94c01d79b07d95849c73e8798911d46bc7
                    remote: https://github.com/Stray-Weights/Dlthon_01_Motocycle_Night_Ride.git
                gpu: NVIDIA GeForce RTX 4070 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7168
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 SUPER
                      uuid: GPU-91a6ce49-4b88-0aaa-c595-01c560f8eedf
                host: D1000BK
                memory:
                    total: "33934004224"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\ADMIN\Documents\projects\team\Dlthon_01_Motocycle_Night_Ride\jong-ha\resnet50_baseline_aug.ipynb
                python: CPython 3.12.9
                root: c:\Users\ADMIN\Documents\projects\team\Dlthon_01_Motocycle_Night_Ride\jong-ha
                startedAt: "2026-02-12T13:25:41.787838Z"
                writerId: s07fdgbwns03dzusbamap4ybv49qqjpx
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 74
                - 80
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 63
                - 74
                - 80
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.9
            "5": 0.24.2
            "8":
                - 1
                - 3
            "12": 0.24.2
            "13": windows-amd64
architecture:
    value: DeepLabV3_ResNet50
batch_size:
    value: 4
epochs:
    value: 50
learning_rate:
    value: 0.0001
